# exp config
n_epochs = 500
batch_size = 1000000
seed = 42
device = "cuda"
exp_name = "disc_seq_inferring_mlp"
wandb_project = "hoge"
use_tqdm = true

# common config
lr = 1e-3
length = 2
n_values = 50
latent_dim = 256
embed_dim = 64
reinforce = false
baseline = "batch_mean"
entropy_weight = 0.01

# encoder config
encoder_hidden_dim = 256
encoder_activation = "relu"
encoder_use_layer_norm = true
encoder_use_residual = true
encoder_n_blocks = 1

# decoder config
decoder_hidden_dim = 256
decoder_activation = "relu"
decoder_use_layer_norm = true
decoder_use_residual = true
decoder_n_blocks = 1
