# exp config
n_epochs = 500
batch_size = 1000000
seed = 42
device = "cuda"
zoo_name = "inferring_with_transformer"
wandb_project = "hoge"
use_tqdm = true

# common config
lr = 1e-3
length = 2
n_values = 50
latent_dim = 256
use_reinforce = false
baseline = "batch_mean"
entropy_weight = 0.01

# encoder config
encoder_embed_dim = 64
encoder_n_heads = 4
encoder_ff_dim = 128
encoder_dropout = 0.1
encoder_activation = "relu"
encoder_layer_norm_eps = 1e-5
encoder_n_layers = 2

# decoder config
decoder_embed_dim = 64
decoder_n_heads = 4
decoder_ff_dim = 128
decoder_dropout = 0.1
decoder_activation = "relu"
decoder_layer_norm_eps = 1e-5
decoder_n_layers = 2
