target = "int_sequence_reconstruction/mlp"

n_epochs = 1001
batch_size = 100000
device = "cuda"
seed = 42
wandb_project = "int_sequence_reconstruction"
use_tqdm = true

lr = 0.001
length = 2
n_values = 50

metrics_interval = 5

latent_dim = 64
encoder_embed_dim = 8
encoder_hidden_dim = 64
encoder_n_layers = 2
encoder_activation = "gelu"
decoder_embed_dim = 8
decoder_hidden_dim = 64
decoder_n_layers = 2
decoder_activation = "gelu"
