# exp config
n_epochs = 500
batch_size = 1000000
seed = 42
device = "cuda"
wandb_project = "hoge"

# common config
lr = 1e-3
length = 2
n_values = 50
latent_dim = 256

# encoder config
encoder_hidden_dim = 256
encoder_embed_dim = 64
encoder_rnn_type = "gru"
n_encoder_layers = 2

# decoder config
decoder_hidden_dim = 256
decoder_embed_dim = 64
decoder_rnn_type = "gru"
n_decoder_layers = 2
