method = "bayes"
name = "two-agents-hypera-search"
project = "CoLingo"

[metric]
name = "test.A0->A1.acc_comp"
goal = "maximize"


[parameters.n_epochs]
value = 1000

[parameters.batch_size]
value = 10000

[parameters.device]
value = "cuda"

[parameters.zoo_name]
value = "signaling_with_mlp_rnn"

[parameters.wandb_project]
value = "CoLingo"

[parameters.use_tqdm]
value = false

[parameters.lr]
value = 0.0002

[parameters.object_length]
value = 2

[parameters.object_n_values]
value = 50

[parameters.message_length]
value = 10

[parameters.message_n_values]
value = 50

[parameters.latent_dim]
value = 256

[parameters.use_reinforce]
value = false

[parameters.baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.1

[parameters.n_agents]
value = 2

[parameters.mlp_encoder_hidden_dim]
min = 64
max = 256

[parameters.mlp_encoder_embed_dim]
value = 64

[parameters.mlp_encoder_activation]
value = "gelu"

[parameters.mlp_encoder_use_layer_norm]
value = false

[parameters.mlp_encoder_use_residual]
value = false

[parameters.mlp_encoder_n_blocks]
value = 0

[parameters.mlp_decoder_hidden_dim]
min = 64
max = 256

[parameters.mlp_decoder_activation]
value = "gelu"

[parameters.mlp_decoder_use_layer_norm]
value = false

[parameters.mlp_decoder_use_residual]
value = false

[parameters.mlp_decoder_n_blocks]
value = 0

[parameters.rnn_encoder_hidden_dim]
min = 64
max = 256

[parameters.rnn_encoder_embed_dim]
value = 64

[parameters.rnn_encoder_rnn_type]
value = "gru"

[parameters.rnn_encoder_n_layers]
value = 2

[parameters.rnn_decoder_hidden_dim]
min = 64
max = 256

[parameters.rnn_decoder_embed_dim]
value = 64

[parameters.rnn_decoder_rnn_type]
value = "gru"

[parameters.rnn_decoder_n_layers]
value = 2

[parameters.synchronize_weight]
value = 0.0
