method = "grid"
name = "syncronize-weight-search"
project = "CoLingo"

[metric]
name = "test.A0->A1.acc_comp"
goal = "maximize"


[parameters.seed]
values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[parameters.n_epochs]
value = 2000

[parameters.batch_size]
value = 10000

[parameters.device]
value = "cuda"

[parameters.zoo_name]
value = "signaling_with_mlp_rnn"

[parameters.wandb_project]
value = "CoLingo"

[parameters.use_tqdm]
value = false

[parameters.lr]
value = 0.0002

[parameters.object_length]
value = 2

[parameters.object_n_values]
value = 50

[parameters.message_length]
value = 10

[parameters.message_n_values]
value = 50

[parameters.latent_dim]
value = 256

[parameters.use_reinforce]
value = false

[parameters.baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.1

[parameters.n_agents]
value = 2

[parameters.mlp_encoder_hidden_dim]
value = 256

[parameters.mlp_encoder_embed_dim]
value = 64

[parameters.mlp_encoder_activation]
value = "gelu"

[parameters.mlp_encoder_use_layer_norm]
value = false

[parameters.mlp_encoder_use_residual]
value = false

[parameters.mlp_encoder_n_blocks]
value = 0

[parameters.mlp_decoder_hidden_dim]
value = 256

[parameters.mlp_decoder_activation]
value = "gelu"

[parameters.mlp_decoder_use_layer_norm]
value = false

[parameters.mlp_decoder_use_residual]
value = false

[parameters.mlp_decoder_n_blocks]
value = 0

[parameters.rnn_encoder_hidden_dim]
value = 256

[parameters.rnn_encoder_embed_dim]
value = 64

[parameters.rnn_encoder_rnn_type]
value = "gru"

[parameters.rnn_encoder_n_layers]
value = 2

[parameters.rnn_decoder_hidden_dim]
value = 256

[parameters.rnn_decoder_embed_dim]
value = 64

[parameters.rnn_decoder_rnn_type]
value = "gru"

[parameters.rnn_decoder_n_layers]
value = 2

[parameters.synchronize_weight]
values = [
    0.0000,
    0.0001,
    0.0002,
    0.0003,
    0.0004,
    0.0005,
    0.0006,
    0.0007,
    0.0008,
    0.0009,
    0.001,
    0.002,
    0.003,
    0.004,
    0.005,
    0.006,
    0.007,
    0.008,
    0.009,
    0.01,
    0.02,
    0.03,
    0.04,
    0.05,
    0.06,
    0.07,
    0.08,
    0.09,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
]
