method = "random"
name = "rnn-encoder-hidden-sweep"
project = "CoLingo"

[metric]
name = "test.signaling_loss.mean"
goal = "minimize"

[parameters.latent_dim]
value = 512

[parameters.n_agents]
value = 2

[parameters.mlp_encoder_embed_dim]
value = 64

[parameters.mlp_encoder_hidden_dim]
value = 256

[parameters.mlp_encoder_activation]
value = "relu"

[parameters.mlp_encoder_n_layers]
value = 2

[parameters.mlp_decoder_hidden_dim]
value = 256

[parameters.mlp_decoder_n_layers]
value = 2

[parameters.mlp_decoder_activation]
value = "relu"

[parameters.rnn_encoder_hidden_dim]
min = 8
max = 256

[parameters.rnn_encoder_embed_dim]
value = 64

[parameters.rnn_encoder_rnn_type]
value = "gru"

[parameters.rnn_encoder_n_layers]
value = 2

[parameters.rnn_decoder_hidden_dim]
value = 256

[parameters.rnn_decoder_embed_dim]
value = 64

[parameters.rnn_decoder_rnn_type]
value = "gru"

[parameters.rnn_decoder_n_layers]
value = 2

[parameters.n_epochs]
value = 500

[parameters.batch_size]
value = 100000

[parameters.device]
value = "cuda"

[parameters.zoo_name]
value = "signaling_with_mlp_rnn"

[parameters.wandb_project]
value = "CoLingo"

[parameters.use_tqdm]
value = true

[parameters.lr]
value = 0.0002

[parameters.object_length]
value = 2

[parameters.object_n_values]
value = 50

[parameters.message_length]
value = 10

[parameters.message_n_values]
value = 50

# [parameters.seed]
# values = [1, 2, 3, 4, 5]

[parameters.run_sender_output]
value = false

[parameters.run_receiver_send]
value = false

[parameters.run_sender_auto_encoding]
value = false

[parameters.run_receiver_auto_encoding]
value = false

[parameters.receiver_loss_weight]
value = 1.0

[parameters.sender_loss_weight]
value = 1.0

[parameters.baseline]
value = "batch_mean"

[parameters.length_baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.0

[parameters.length_weight]
value = 0.0

# [parameters.raece_loss_weight]
# value = 1.0

# [parameters.rmce_loss_weight]
# value= = 1.0

# [parameters.saece_loss_weight]
# value =  1.0

# [parameters.soce_loss_weight]
# value = 1.0

# [parameters.saecel_loss_weight]
# value = 1.0

[parameters.eval_interval]
value = 20

[parameters.acc_heatmap_interval]
value = 5

[parameters.topsim_interval]
value = 5

[parameters.lansim_interval]
value = 200

[parameters.lansim_heatmap_interval]
value = 1

[parameters.language_save_interval]
value = 400
