method = "random"
name = "length_penalty_search"
project = "CoLingo"

[metric]
name = "signal_valid.A1 -> A1.concept_accuracy.complete"
goal = "maximize"

[parameters.exp_name]
value = "exp1"

[parameters.n_iterations]
value = 1000

[parameters.batch_size]
value = 65536

[parameters.seed]
value = 3

[parameters.device]
value = "cuda"

[parameters.model_save_interval]
value = 1000

[parameters.wandb_project]
value = "CoLingo"

[parameters.wandb_name]
value = "run"

[parameters.n_attributes]
value = 2

[parameters.n_values]
value = 50

[parameters.max_len]
value = 10

[parameters.vocab_size]
value = 50

[parameters.internal_dim]
value = 512

[parameters.concept_embed_dim]
value = 64

[parameters.concept_hidden_dim]
value = 256

[parameters.message_embed_dim]
value = 64

[parameters.rnn_type]
value = "gru"

[parameters.message_hidden_dim]
value = 256

[parameters.n_layers]
value = 2

[parameters.share_message_embedding]
value = false

[parameters.optimizer]
value = "adam"

[parameters.lr]
value = 0.001

[parameters.split_ratio]
value = 0.8

[parameters.baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.1

[parameters.length_weight]
min = 0.0
max = 2.0

[parameters.run_single]
value = false

[parameters.run_signal]
value = true

[parameters.max_batches_single]
value = 1

[parameters.max_batches_signal]
value = 1
