method = "random"
name = "loss_scaling_search"
project = "CoLingo"

[metric]
name = "lang.lansim.mean"
goal = "maximize"

[parameters.exp_name]
value = "exp1"

[parameters.n_iterations]
value = 5000

[parameters.batch_size]
value = 65536

[parameters.seed]
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[parameters.device]
value = "cuda"

[parameters.model_save_interval]
value = 1000

[parameters.eval_interval]
value = 20

[parameters.wandb_project]
value = "CoLingo"

[parameters.wandb_name]
value = "run"

[parameters.n_attributes]
value = 2

[parameters.n_values]
value = 50

[parameters.max_len]
value = 10

[parameters.vocab_size]
value = 50

[parameters.internal_dim]
value = 512

[parameters.concept_embed_dim]
value = 64

[parameters.concept_hidden_dim]
value = 256

[parameters.message_embed_dim]
value = 64

[parameters.rnn_type]
value = "gru"

[parameters.message_hidden_dim]
value = 256

[parameters.n_layers]
value = 2

[parameters.share_message_embedding]
value = true

[parameters.n_agents]
value = 2

[parameters.optimizer]
value = "adam"

[parameters.lr]
value = 0.001

[parameters.split_ratio]
value = 0.8

[parameters.baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.1

[parameters.length_weight]
value = 0.0

[parameters.max_batches_signal]
value = 1

[parameters.sender_output]
value = true

[parameters.sender_receive]
value = true

[parameters.receiver_send]
value = true

[parameters.receiver_input]
value = true

[parameters.sender_message_loss_weight]
min = 0.0
max = 1.0

[parameters.receiver_output_loss_weight]
min = 0.0
max = 1.0

[parameters.sender_output_loss_weight]
min = 0.0
max = 1.0

[parameters.receiver_message_loss_weight]
min = 0.0
max = 1.0

[parameters.receiver_latent_loss_weight]
min = 0.0
max = 1.0

[parameters.sender_latent_loss_weight]
min = 0.0
max = 1.0
