method = "random"
name = "seed_sweep"
project = "CoLingo"

[metric]
name = "signal_valid.A1 -> A1.acc.complete"
goal = "maximize"

[parameters.exp_name]
value = "exp1"

[parameters.n_iterations]
value = 4000

[parameters.batch_size]
value = 65536

[parameters.device]
value = "cpu"

[parameters.model_save_interval]
value = 1000

[parameters.n_attributes]
value = 2

[parameters.n_values]
value = 50

[parameters.max_len]
value = 10

[parameters.vocab_size]
value = 50

[parameters.internal_size]
value = 1024

[parameters.embed_size]
value = 128

[parameters.hidden_size]
value = 256

[parameters.rnn_type]
value = "gru"

[parameters.n_layers]
value = 2

[parameters.share_message_embedding]
value = true

[parameters.optimizer]
value = "adam"

[parameters.lr]
value = 0.001

[parameters.split_ratio]
value = 0.8

[parameters.baseline]
value = "batch_mean"

[parameters.entropy_weight]
value = 0.5

[parameters.length_weight]
value = 0.0

[parameters.run_single]
value = true

[parameters.run_signal]
value = true

[parameters.max_batches_single]
value = 1

[parameters.max_batches_signal]
value = 1

[parameters.seed]
min = 0
max = 100000
