zoo = "reco_network"
seed = 42

concept_length = 2
concept_values = 30
train_proportion = 0.8
valid_proportion = 0.2
message_max_len = 8
message_vocab_size = 50
entropy_weight = 0.01
length_weight = 0.0
receiver_loss_weight = 1.0
sender_loss_weight = 1.0
sender_imitation_loss_weight = 1.0
n_epochs = 5001
batch_size = 100000
lr = 0.001
device = "cuda"
wandb_project = "reco_network"
use_tqdm = true
metrics_interval = 10
topsim_interval = 100
lang_log_interval = 100
acc_heatmap_interval = 100
lansim_interval = 100

network_type = "ring"

agents_mode = "uniform"
n_agents = 3

[agent_config]
latent_dim = 64
concept_encoder_type = "mlp"
concept_decoder_type = "mlp"
message_encoder_type = "transformer"
message_decoder_type = "transformer"

[agent_config.concept_encoder_params]
embed_dim = 8
hidden_dim = 64
n_layers = 2
activation = "gelu"

[agent_config.concept_decoder_params]
hidden_dim = 64
n_layers = 2
activation = "gelu"

[agent_config.message_encoder_params]
embed_dim = 64
n_heads = 8
ff_dim = 64
dropout = 0.01
activation = "gelu"
layer_norm_eps = 1e-5
norm_first = false
n_layers = 2
is_causal = false

[agent_config.message_decoder_params]
embed_dim = 64
n_heads = 8
ff_dim = 64
dropout = 0.01
activation = "gelu"
layer_norm_eps = 1e-5
norm_first = false
n_layers = 2
