method = "bayes"
name = "reconstruction_transformer_bayes"
project = "reconstruction"

[metric]
name = "test.acc_part"
goal = "maximize"

[parameters.zoo]
value = "reconstruction_transformer"

[parameters.n_epochs]
value = 1001

[parameters.batch_size]
value = 100000

[parameters.device]
value = "cuda"

# [parameters.seed]
# value = 42

[parameters.wandb_project]
value = "reconstruction"

[parameters.use_tqdm]
value = false

[parameters.lr]
value = 0.001

[parameters.length]
value = 2

[parameters.values]
value = 50

[parameters.metrics_interval]
value = 5

[parameters.latent_dim]
values = [8, 16, 32, 64, 128, 256]

[parameters.encoder_embed_dim]
values = [8, 16, 32, 64, 128, 256]

[parameters.encoder_n_heads]
values = [1, 2, 4, 8]

[parameters.encoder_ff_dim]
values = [8, 16, 32, 64, 128, 256, 512]

[parameters.encoder_dropout]
value = 0.0

[parameters.encoder_activation]
value = "relu"

[parameters.encoder_layer_norm_eps]
value = 1e-5

[parameters.encoder_norm_first]
value = false

[parameters.encoder_n_layers]
values = [1, 2, 3, 4]

[parameters.encoder_is_causal]
value = false

[parameters.decoder_embed_dim]
values = [8, 16, 32, 64, 128, 256]

[parameters.decoder_n_heads]
values = [1, 2, 4, 8]

[parameters.decoder_ff_dim]
values = [8, 16, 32, 64, 128, 256, 512]

[parameters.decoder_dropout]
value = 0.0

[parameters.decoder_activation]
value = "relu"

[parameters.decoder_layer_norm_eps]
value = 1e-5

[parameters.decoder_norm_first]
value = false

[parameters.decoder_n_layers]
values = [1, 2, 3, 4]
