exp_name = "exp1"
n_iterations = 100
batch_size = 65536
seed = 42
device = "cuda"
model_save_interval = 1000
data_size = 1000

# wandb
wandb_project = "hoge"
wandb_name = "huga"

# channel
max_len = 10
vocab_size = 50

# model
internal_dim = 512
concept_embed_dim = 64
concept_hidden_dim = 256
message_embed_dim = 64
rnn_type = "gru"
message_hidden_dim = 256
n_layers = 2
share_message_embedding = true

# optimizer
optimizer = "adam"
lr = 0.001

# dataset
split_ratio = 0.8
