exp_name: "sample_exp"
n_iterations: 30000
seed: 3
device: "cuda"

concept_config: &concept_config
  n_attributes: 2
  n_values: 50

channel_config: &channel_config
  type: "ecsem"
  <<: *concept_config
  vocab_size: 50
  max_len: 3

datasets:
  dataset1:
    type: "concept"
    <<: *concept_config
    split:
      train: 8
      val: 2

agents:
  agent1:
    model:
      type: "ecsem"
      <<: *channel_config
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    optimizer:
      type: "adam"
      lr: 0.001
  agent2:
    model:
      type: "ecsem"
      <<: *channel_config
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    optimizer:
      type: "adam"
      lr: 0.001
tasks:
  task1:
    type: "signaling"
    dataloader:
      type: "builtin"
      dataset: "dataset1_train"
      batch_size: 32
      shuffle: true
    network:
      type: "custom"
      edges:
        - { "source": "agent1", "target": "agent2" }
    sender_loss:
      type: "reinforce"
      entropy_weight: 0.5
      baseline:
        type: "batch_mean"
      length_baseline:
        type: "batch_mean"
    receiver_loss:
      type: "concept"
      <<: *concept_config
