# 学習全体の設定
[training]
n_epochs = 20000
seed = 3
device = "cpu"


# データセットの定義
[datasets.onehots1]
type = "onehots"
[datasets.onehots1.args]
n_attributes = 1
n_values = 10

[datasets.normal1]
type = "normal"
[datasets.normal1.args]
n_dim = 2
mean = 0.0
std = 1.0

# データーローダーの定義
[dataloaders.onehots_loader1]
type = "default"
[dataloaders.onehots_loader1.args]
dataset = "onehots1"
batch_size = 32
shuffle = true


# ネットワークの定義
[networks.custom_net1]
type = "custom"
[[networks.custom_net1.args.edges]]
source = "S01"
target = "R01"
# [[networks.custom_net1.args.edges]]
# source = "S01"
# target = "R02"

# モデルの定義
[models.single_word1]
type = "single_word"
[models.single_word1.args]
n_attributes = 1
n_values = 5
vocab_size = 20
hidden_size = 512

[models.sequence1]
type = "sequence"
[models.sequence1.args]
n_attributes = 1
n_values = 10
vocab_size = 20
max_len = 3

# ベースラインの定義
[baselines.mean]
type = "mean"
[baselines.mean.args]


# タスクの定義
[tasks.lewis1]
type = "lewis"
[tasks.lewis1.args]
dataloader = "onehots_loader1"
network = "custom_net1"

# エージェントの定義
[agents.S01]
type = "agent"
[agents.S01.args]
model = "sequence1"
baseline = "mean"
optimizer_type = "adam"
[agents.S01.args.optimizer_args]
lr = 0.001


# エージェントの定義
[agents.R01]
type = "agent"
[agents.R01.args]
model = "sequence1"
baseline = "mean"
optimizer_type = "adam"
[agents.R01.args.optimizer_args]
lr = 0.001


# エージェントの定義
[agents.R02]
type = "agent"
[agents.R02.args]
model = "single_word1"
baseline = "mean"
optimizer_type = "adam"
[agents.R02.args.optimizer_args]
lr = 0.001
