# 学習全体の設定
[training]
n_epochs = 20000
seed = 3
device = "cpu"


# データセットの定義
[datasets.onehots1]
type = "onehots"
[datasets.onehots1.args]
n_attributes = 1
n_values = 5

[datasets.normal1]
type = "normal"
[datasets.normal1.args]
n_dim = 2
mean = 0.0
std = 1.0

# データーローダーの定義
[dataloaders.onehots_loader1]
type = "default"
dataset = "onehots1"
[dataloaders.onehots_loader1.args]
batch_size = 32
shuffle = true


# ネットワークの定義
[networks.custom_net1]
type = "custom"
[[networks.custom_net1.args.edges]]
source = "S01"
target = "R01"
# [[networks.custom_net1.args.edges]]
# source = "S01"
# target = "R02"

# モデルの定義
[models.single_word1]
type = "single_word"
[models.single_word1.args]
n_attributes = 1
n_values = 5
vocab_size = 20
hidden_size = 512

[models.sequence1]
type = "sequence"
[models.sequence1.args]
n_attributes = 1
n_values = 5
vocab_size = 20
max_len = 3


# ゲームの定義
[games.lewis1]
type = "lewis"
play_rate = 1.0
dataloader = "onehots_loader1"
network = "custom_net1"
[games.lewis1.args]

# エージェントの定義
[agents.S01]
type = "onehots_single_word"
model = "sequence1"
[agents.S01.args]
optimizer_type = "adam"
baseline_type = "mean"
[agents.S01.args.optimizer_args]
lr = 0.001
[agents.S01.args.baseline_args]


# エージェントの定義
[agents.R01]
type = "onehots_single_word"
model = "sequence1"
[agents.R01.args]
optimizer_type = "adam"
baseline_type = "mean"
[agents.R01.args.optimizer_args]
lr = 0.001
[agents.R01.args.baseline_args]


# エージェントの定義
[agents.R02]
type = "onehots_single_word"
model = "single_word1"
[agents.R02.args]
optimizer_type = "adam"
baseline_type = "mean"
[agents.R02.args.optimizer_args]
lr = 0.001
[agents.R02.args.baseline_args]
