exp_name: "sample_exp"
n_epochs: 3000
seed: 3
device: "cpu"

onehots_config: &onehots_config
  n_attributes: 2
  n_values: 50

datasets:
  dataset1:
    type: "onehots"
    <<: *onehots_config

agents:
  agent1:
    model:
      type: "sequence"
      <<: *onehots_config
      vocab_size: 50
      max_len: 3
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    tasks:
      task1:
        optimizer:
          type: "adam"
          lr: 0.001
        loss:
          type: "reinforce"
          entropy_weight: 0.01
          baseline:
            type: "mean"
          length_baseline:
            type: "mean"
  agent2:
    model:
      type: "sequence"
      <<: *onehots_config
      vocab_size: 50
      max_len: 3
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    tasks:
      task1:
        optimizer:
          type: "adam"
          lr: 0.001
        loss:
          type: "concept"
          <<: *onehots_config
tasks:
  task1:
    type: "communication"
    dataloader:
      type: "default"
      dataset: "dataset1"
      batch_size: 32
      shuffle: true
    network:
      type: "custom"
      edges:
        - { "source": "agent1", "target": "agent2" }
