exp_name: "sample_exp"
n_iterations: 30000
seed: 3
device: "cuda"

concept_config: &concept_config
  n_attributes: 2
  n_values: 50

channel_config: &channel_config
  <<: *concept_config
  max_len: 10
  vocab_size: 50

model_config: &model_config
  type: "internal"
  <<: *channel_config
  internal_size: 256
  embed_size: 256
  hidden_size: 256
  rnn_type: "gru"
  n_layers: 2
  share_message_embedding: true

optimizer_config: &optimizer_config
  type: "adam"
  lr: 0.001

dataloader_config: &dataloader_config
  type: "builtin"
  dataset: "dataset1_train"
  batch_size: 8192
  shuffle: true

network_config: &network_config
  type: "custom"
  nodes:
    - "agent1"
    - "agent2"
  edges:
    - ["agent1", "agent2"]
    - ["agent2", "agent1"]

metrics_config: &metrics_config
  acc:
    type: "concept_accuracy"
    <<: *concept_config

loggers_config: &loggers_config
  console:
    type: "console"
  wandb:
    type: "wandb"
    project: "hoge"
    name: "huga"
    tags:
      - "piyo_tag"
      - "fuga_tag"

datasets:
  dataset1:
    type: "concept"
    <<: *concept_config
    split:
      train: 8
      val: 2

agents:
  agent1:
    model:
      <<: *model_config
    optimizer:
      <<: *optimizer_config
  agent2:
    model:
      <<: *model_config
    optimizer:
      <<: *optimizer_config
tasks:
  signaling1:
    type: "signaling"
    dataloader:
      <<: *dataloader_config
      dataset: "dataset1_train"
    network:
      <<: *network_config
    sender_loss:
      type: "reinforce"
      entropy_weight: 0.5
      length_weight: 0.01
      baseline:
        type: "batch_mean"
      length_baseline:
        type: "batch_mean"
    receiver_loss:
      type: "concept"
      <<: *concept_config
    max_batches: 1

  identity1:
    type: "identity"
    dataloader:
      <<: *dataloader_config
    network:
      <<: *network_config
    loss:
      type: "concept"
      <<: *concept_config
    max_batches: 1

  signaling_train_eval:
    type: "signaling_eval"
    network:
      <<: *network_config
    dataset: "dataset1_train"
    metrics:
      <<: *metrics_config
      msglen:
        type: "msglen"
      msgent:
        type: "msgent"
    loggers:
      <<: *loggers_config
    interval: 1

  signaling_val_eval:
    type: "signaling_eval"
    network:
      <<: *network_config
    dataset: "dataset1_val"
    metrics:
      <<: *metrics_config
      msglen:
        type: "msglen"
      msgent:
        type: "msgent"
    loggers:
      <<: *loggers_config
    interval: 1

  identity_train_eval:
    type: "identity_eval"
    network:
      <<: *network_config
    dataset: "dataset1_train"
    metrics:
      <<: *metrics_config
    loggers:
      <<: *loggers_config
    interval: 1

  identity_val_eval:
    type: "identity_eval"
    network:
      <<: *network_config
    dataset: "dataset1_val"
    metrics:
      <<: *metrics_config
    loggers:
      <<: *loggers_config
    interval: 1

  # language_eval:
  #   type: "language_eval"
  #   network:
  #     <<: *network_config
  #   dataset: "dataset1"
  #   metrics:
  #     topsim:
  #       type: "topsim"
  #     langsim:
  #       type: "langsim"
  #   loggers:
  #     <<: *loggers_config
  #   interval: 1
