exp_name: "sample_exp"
n_epochs: 30000
seed: 3
device: "cuda"

onehots_config: &onehots_config
  n_attributes: 2
  n_values: 50

datasets:
  dataset1:
    type: "concept"
    <<: *onehots_config

agents:
  agent1:
    model:
      type: "ecsem"
      <<: *onehots_config
      vocab_size: 50
      max_len: 3
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    optimizer:
      type: "adam"
      lr: 0.001
  agent2:
    model:
      type: "ecsem"
      <<: *onehots_config
      vocab_size: 50
      max_len: 3
      hidden_size: 512
      rnn_type: "gru"
      n_layers: 2
      embed_size: 64
    optimizer:
      type: "adam"
      lr: 0.001
tasks:
  task1:
    type: "signaling"
    dataloader:
      type: "builtin"
      dataset: "dataset1"
      batch_size: 32
      shuffle: true
    network:
      type: "custom"
      edges:
        - { "source": "agent1", "target": "agent2" }
    sender_loss:
      type: "reinforce"
      entropy_weight: 0.5
      baseline:
        type: "batch_mean"
      length_baseline:
        type: "batch_mean"
    receiver_loss:
      type: "concept"
      <<: *onehots_config
