exp_name = "exp1"
n_iterations = 1000
batch_size = 65536
seed = 42
device = "cuda"
model_save_interval = 1000
eval_interval = 20

# wandb
wandb_project = "hoge"
wandb_name = "huga"


# concept 
n_attributes = 2
n_values = 50

# channel
max_len = 10
vocab_size = 50

# model
internal_dim = 512
concept_embed_dim = 64
concept_hidden_dim = 256
message_embed_dim = 64
rnn_type = "gru"
message_hidden_dim = 256
n_layers = 2
share_message_embedding = true

n_agents = 2

# optimizer
optimizer = "adam"
lr = 0.001

# dataset
split_ratio = 0.8

# reinforce
baseline = "batch_mean"
entropy_weight = 0.1
length_weight = 0.0

# task
max_batches_signal = 1

# option 
sender_output = false
sender_receive = false
receiver_send = false
receiver_input = false

receiver_ruminate = true

# weight
sender_message_loss_weight = 1.0
receiver_output_loss_weight = 1.0
sender_output_loss_weight = 1.0
receiver_message_loss_weight = 1.0
receiver_latent_loss_weight = 1.0
sender_latent_loss_weight = 1.0
