exp_name = "exp1"
n_iterations = 1000
batch_size = 65536
seed = 3
device = "cuda"
model_save_interval = 1000

# wandb
wandb_project = "hoge"
wandb_name = "huga"


# concept 
n_attributes = 2
n_values = 50

# channel
max_len = 10
vocab_size = 50

# model
internal_dim = 1024
concept_embed_dim = 128
concept_hidden_dim = 256
message_embed_dim = 128
rnn_type = "gru"
message_hidden_dim = 256
n_layers = 2
share_message_embedding = false

# optimizer
optimizer = "adam"
lr = 0.001

# dataset
split_ratio = 0.8

# reinforce
baseline = "batch_mean"
entropy_weight = 0.5
length_weight = 0.0

# task
run_single = false
run_signal = true
max_batches_single = 1
max_batches_signal = 1
