# common config
latent_dim = 150
n_agents = 2

# mlp encoder config
mlp_encoder_embed_dim = 8
mlp_encoder_hidden_dim = 150
mlp_encoder_n_layers = 2
mlp_encoder_activation = "gelu"

# mlp decoder config
mlp_decoder_hidden_dim = 150
mlp_decoder_n_layers = 2
mlp_decoder_activation = "gelu"

# rnn encoder config
rnn_encoder_hidden_dim = 150
rnn_encoder_embed_dim = 8
rnn_encoder_rnn_type = "gru"
rnn_encoder_n_layers = 2

# rnn decoder config
rnn_decoder_hidden_dim = 150
rnn_decoder_embed_dim = 8
rnn_decoder_rnn_type = "gru"
rnn_decoder_n_layers = 2

# exp config
n_epochs = 2000
batch_size = 100000
device = "cuda"
zoo_name = "signaling_with_mlp_rnn"
wandb_project = "hoge"
use_tqdm = true

# common config
lr = 0.001
object_length = 2
object_n_values = 40
message_length = 8
message_n_values = 40

# optional config
seed = 42

run_sender_output = false
run_receiver_send = false
run_sender_auto_encoding = false
run_receiver_auto_encoding = true

baseline = "batch_mean"
length_baseline = "batch_mean"
entropy_weight = 0.01
length_weight = 0.0

roce_loss_weight = 1.0
raece_loss_weight = 1.0
# rmce_loss_weight = 1.0
smrf_loss_weight = 1.0
# saece_loss_weight = 1.0
# soce_loss_weight = 1.0
# saecel_loss_weight = 1.0

eval_interval = 20
acc_heatmap_interval = 5
topsim_interval = 5
lansim_interval = 100
lansim_heatmap_interval = 1
language_save_interval = 400
