# common config
latent_dim = 512
n_agents = 2

# mlp encoder config
mlp_encoder_hidden_dim = 256
mlp_encoder_embed_dim = 64
mlp_encoder_activation = "relu"
mlp_encoder_use_layer_norm = false
mlp_encoder_use_residual = false
mlp_encoder_n_blocks = 0

# mlp decoder config
mlp_decoder_hidden_dim = 128
mlp_decoder_activation = "relu"
mlp_decoder_use_layer_norm = false
mlp_decoder_use_residual = false
mlp_decoder_n_blocks = 0

# rnn encoder config
rnn_encoder_hidden_dim = 128
rnn_encoder_embed_dim = 64
rnn_encoder_rnn_type = "gru"
rnn_encoder_n_layers = 2

# rnn decoder config
rnn_decoder_hidden_dim = 256
rnn_decoder_embed_dim = 64
rnn_decoder_rnn_type = "gru"
rnn_decoder_n_layers = 2

# exp config
n_epochs = 1000
batch_size = 100000
device = "cuda"
zoo_name = "signaling_with_mlp_rnn"
wandb_project = "hoge"
use_tqdm = true

# common config
lr = 0.0002
object_length = 2
object_n_values = 50
message_length = 10
message_n_values = 10

# optional config
seed = 42

run_sender_output = true
run_receiver_send = true
run_sender_auto_encoding = false
run_receiver_auto_encoding = false

receiver_loss_weight = 1.0

sender_loss_weight = 1.0
baseline = "batch_mean"
length_baseline = "batch_mean"
entropy_weight = 0.0
length_weight = 0.0

# raece_loss_weight = 1.0
rmce_loss_weight = 1.0
# saece_loss_weight = 1.0
soce_loss_weight = 1.0

eval_interval = 10
acc_heatmap_interval = 5
topsim_interval = 5
lansim_interval = 50
lansim_heatmap_interval = 1
