method = "grid"
name = "reco_network_mlp_transformer"
project = "reco_network"

[metric]
name = "test.topsim.mean"
goal = "maximize"

[parameters.zoo]
value = "reco_network_mlp_transformer"

[parameters.n_epochs]
value = 5001

[parameters.batch_size]
value = 100000

[parameters.device]
value = "cuda"

[parameters.seed]
values = [1, 2, 3, 4, 5]

[parameters.wandb_project]
value = "reco_network"

[parameters.use_tqdm]
value = false

[parameters.lr]
value = 0.001

[parameters.object_length]
value = 2

[parameters.object_values]
value = 30

[parameters.message_max_len]
value = 8

[parameters.message_vocab_size]
value = 50

[parameters.entropy_weight]
value = 0.01

[parameters.length_weight]
value = 0.0

[parameters.metrics_interval]
value = 10

[parameters.topsim_interval]
value = 100

[parameters.language_log_interval]
value = 100

[parameters.acc_heatmap_interval]
value = 100

[parameters.lansim_interval]
value = 100

[parameters.decoder_ae]
values = [0, 1]

[parameters.n_agents]
value = 4

[parameters.network_window]
values = [1, 2, 3, 4]

[parameters.latent_dim]
value = 64

[parameters.object_encoder_embed_dim]
value = 8

[parameters.object_encoder_hidden_dim]
value = 64

[parameters.object_encoder_n_layers]
value = 2

[parameters.object_encoder_activation]
value = "gelu"

[parameters.object_decoder_hidden_dim]
value = 64

[parameters.object_decoder_n_layers]
value = 2

[parameters.object_decoder_activation]
value = "gelu"

[parameters.message_encoder_embed_dim]
value = 64

[parameters.message_encoder_n_heads]
value = 8

[parameters.message_encoder_ff_dim]
value = 64

[parameters.message_encoder_dropout]
value = 0.01

[parameters.message_encoder_activation]
value = "gelu"

[parameters.message_encoder_layer_norm_eps]
value = 1e-5

[parameters.message_encoder_norm_first]
value = false

[parameters.message_encoder_n_layers]
value = 2

[parameters.message_encoder_is_causal]
value = false

[parameters.message_decoder_embed_dim]
value = 64

[parameters.message_decoder_n_heads]
value = 8

[parameters.message_decoder_ff_dim]
value = 64

[parameters.message_decoder_dropout]
value = 0.01

[parameters.message_decoder_activation]
value = "gelu"

[parameters.message_decoder_layer_norm_eps]
value = 1e-5

[parameters.message_decoder_norm_first]
value = false

[parameters.message_decoder_n_layers]
value = 2
